### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by prabhant** [mononitogoswami/tsad-model-selection#1]
Hi thanks for making the code public, can you also add the instructions on how can we reproduce the results from the paper experiments

**Comment by mononitogoswami** [comment]
Hi Prabhant, 
Thank you for your interest! We are working on making changes to the code and the readme to ensure reproducibility. 

Currently, you can run our script (tsad-model-selection > src > scripts) to train (all) models (train_all_models.py) and evaluate them (evaluate_all_models). Finally, the results can be viewed using the results jupyter notebook. 

Thanks!

**Comment by mononitogoswami** [comment]
I added some steps to reproduce the results of the paper, let me know if I can add more details!
