### ISSUE TITLE
ModuleNotFoundError: No module named 'model_selection'

### ISSUE THREAD

**Issue by ripankundu** [mononitogoswami/tsad-model-selection#2]
Hi,

I am trying to reproduce the work. I already installed all the requirements as given in installation. However, when I run the notebook form the test folder it show the following error:
ModuleNotFoundError: No module named 'model_selection'

I am confused why that is happen even I installed everything correctly. Could you please help me to solve the issue

**Comment by mononitogoswami** [comment]
Hi Ripan, 
Installing the code via an editable install might help: 
```
    foo@bar:~$ git clone https://github.com/mononitogoswami/tsad-model-selection.git
    foo@bar:~$ cd tsad-model-selection/src/
    foo@bar:~$ pip install -e .
```
If it doesn't work, let me know and we can look into the issue.
