### ISSUE TITLE
Error in running compute_pooled_results.py

### ISSUE THREAD

**Issue by MaNingning825** [mononitogoswami/tsad-model-selection#3]
Hi thanks for making the code public, I run `evaluate_all_models.py`, and on some data sets of smd, the log:
 `Error in evaluating models on entity:machine-1-6` . When I `run compute_pooled_results.py`, the `len(ranking_obj.predictions.keys())` is 9 and not equal to `N_MODELS`

**Comment by MaNingning825** [comment]
In `eval_utils.py`, 
```
File "/home/tsadams/utils/eval_utils.py", line 97, in pool_predictions_of_entities
    predictions[mn][q] = np.concatenate(predictions[mn][q], axis=1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```
I find`predictions=[]`

**Comment by mononitogoswami** [comment]
Hi Ningning,
Thanks for your interest in our code!

Regarding `Error in evaluating models on entity: machine-1-6`: You said that you get this error only on some datasets of SMD. I am not sure if I have enough information to help you debug the specific issue, but I am hoping that it is something data specific. I noticed that for some datasets, some trained models might yield such errors. 

Regarding `len(ranking_obj.predictions.keys())`, can you check if all models were trained? Sometimes, some models fail during training. 

For `predictions=[]`, from the information I have, it seems that some model has failed to train, or produce predictions, and hence the prediction dictionary corresponding to that model is empty. 

Overall, I think it would be good to check if all models have finished training successfully, and whether they are providing reasonable predictions by visualizing how well they reconstruct time-series. 

Let me know if you have any more questions, I will close this issue for now, but feel free to open another issue!

**Comment by mononitogoswami** [comment]
Let me know if you face more issues! Feel free to open another issue!

**Comment by MaNingning825** [comment]
The order I run is to first run `download_data.py` to download the data set,
then run `train_all_models.py` to train the model, 
then run `evaluate_all_models.py` to evaluate the model, 
and finally run `compute_pooled_results.py`. 

At the stage of running `evaluate_all_models.py`, I found an error 
```
Can't get attribute 'EuclideanDistance64' on <module 'sklearn.metrics._dist_metrics' from '/home/miniconda3/envs/tsadams/lib/python3.9/site- packages/sklearn/metrics/_dist_metrics.cpython-39-x86_64-linux-gnu.so
```
